package VISTA;

import Controlador.GradoControlador;
import Modelo.Grado;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Estudiantes
 */
public class VistaGrado extends javax.swing.JPanel {

    private final GradoControlador gradoControlador;

    private Integer GradoSeleccionado = null;

    public VistaGrado() {
        initComponents();
        this.gradoControlador = new GradoControlador();
        cargarDatosTabla();
    }

    private void cargarDatosTabla() {
        List<Grado> Grados = gradoControlador.leerTodosGrados();
        if (Grados != null) {
            DefaultTableModel model = (DefaultTableModel) tablaGrado.getModel();
            model.setRowCount(0);
            for (Grado Grad : Grados) {
                Object[] row = {
                    Grad.getID_Grado(),
                    Grad.getDescripcion(),
                    Grad.getSeccion()
                };
                model.addRow(row);
            }
        }
    }

    private void Limpiar() {

        textDescripcion.setText("");
        textSeccion.setText("");
        GradoSeleccionado = null;

        btnEliminar.setEnabled(true);
        btnGuardar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaGrado = new javax.swing.JTable();
        textDescripcion = new javax.swing.JTextField();
        textSeccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textBuscar = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btbActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("jLabel2");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaGrado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Grado", "Descripcion", "Seccion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaGrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaGradoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaGrado);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 227, 498, 200));

        textDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDescripcionActionPerformed(evt);
            }
        });
        jPanel1.add(textDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 45, 160, 30));
        jPanel1.add(textSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 45, 158, 30));

        jLabel4.setText("Buscar");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 111, -1, -1));

        textBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textBuscarKeyTyped(evt);
            }
        });
        jPanel1.add(textBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 104, 200, 30));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionBotonGuardar(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 168, 96, 31));

        btbActualizar.setText("Actualizar");
        btbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionBotonActualizar(evt);
            }
        });
        jPanel1.add(btbActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 168, 90, 32));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionBotonEliminar(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 100, 30));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionBotonLimpiar(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 170, -1, 30));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Descripcion");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 22, -1, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Seccion");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 22, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDescripcionActionPerformed

    private void accionBotonGuardar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionBotonGuardar
        String Descrepcion = textDescripcion.getText();
        String Seccion = textSeccion.getText();

        if (!Descrepcion.isEmpty() && !Seccion.isEmpty()) {

            gradoControlador.crearGrado(Descrepcion, Seccion);
            cargarDatosTabla();

            textDescripcion.setText("");
            textSeccion.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, llene los campos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_accionBotonGuardar

    private void accionBotonActualizar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionBotonActualizar
        String Descrepcion = textDescripcion.getText();
        String Seccion = textSeccion.getText();

        if (!Descrepcion.isEmpty() && !Seccion.isEmpty()) {

            gradoControlador.actualizarGrado(1, Descrepcion, Seccion);
            cargarDatosTabla();

            textDescripcion.setText("");
            textSeccion.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, llene los campos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_accionBotonActualizar

    private void accionBotonEliminar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionBotonEliminar
        int filaSeleccionada = tablaGrado.getSelectedRow();
        if (filaSeleccionada != -1) {
            int ID_Grado = (int) tablaGrado.getValueAt(filaSeleccionada, 0);
            gradoControlador.eliminarGrado(ID_Grado);
            cargarDatosTabla();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona una fila para eliminar.", "error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_accionBotonEliminar

    private void accionBotonLimpiar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionBotonLimpiar
        Limpiar();
    }//GEN-LAST:event_accionBotonLimpiar

    private void textBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textBuscarKeyTyped
        String textoBusqueda = textBuscar.getText().trim().toLowerCase();
        List<Grado> Grados = gradoControlador.leerTodosGrados();

        DefaultTableModel modelo = (DefaultTableModel) tablaGrado.getModel();
        modelo.setRowCount(0);

        if (Grados != null) {
            for (Grado Gra : Grados) {
                if (textoBusqueda.isEmpty()
                        || Gra.getDescripcion().toLowerCase().contains(textoBusqueda)
                        || Gra.getSeccion().toLowerCase().contains(textoBusqueda)) {

                    Object[] fila = {
                        Gra.getID_Grado(),
                        Gra.getDescripcion(),
                        Gra.getSeccion()
                    };
                    modelo.addRow(fila);
                }
            }
        }
    }//GEN-LAST:event_textBuscarKeyTyped

    private void tablaGradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaGradoMouseClicked
        if (evt.getClickCount() == 2) {

            int filaSeleccionada = tablaGrado.getSelectedRow();

            if (filaSeleccionada != -1) {

                GradoSeleccionado = (int) tablaGrado.getValueAt(filaSeleccionada, 0);
                String Descripcion = (String) tablaGrado.getValueAt(filaSeleccionada, 1);
                String Seccion = (String) tablaGrado.getValueAt(filaSeleccionada, 2);

                textDescripcion.setText(Descripcion);
                textSeccion.setText(Seccion);

                btnEliminar.setEnabled(false);
                btnGuardar.setEnabled(false);

            }
        }
    }//GEN-LAST:event_tablaGradoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tablaGrado;
    private javax.swing.JTextField textBuscar;
    private javax.swing.JTextField textDescripcion;
    private javax.swing.JTextField textSeccion;
    // End of variables declaration//GEN-END:variables
}
